site_name: Data Science and ML
site_url: https://mydomain.org
site_author: Santosh Kumar Sah
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 


        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - content.tabs.link
    - header.autohide
    - content.code.annotate     # Enable annotated code
    - content.code.copy         # Add a copy button to code blocks
    - content.code.tabs         # Enable interactive tabs for code blocks
    - content.code.execute      # Enable interactive Python execution

  # palette:
  #   - scheme: default
  #     primary: deep purple
  #     accent: pink
  #   - scheme: slate
  #     primary: deep purple
  #     accent: pink
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/sntoshsah

nav:
  - Home: index.md
  # - About Me: about.md
  - Projects:
      - AI Engineer: projects/ai.md
      - Data Science: projects/data_science.md
  - Learning Resources:
      - Learning_resources/Python/Python_Syntax.md
      - Learning_resources/Python/Python_Basics.md

  - Blog: blog.md
  - Contact: contact.md

plugins:
  - search
  - awesome-pages
  - mkdocs-jupyter
  - markdown-exec
markdown_extensions:
- pymdownx.superfences








