site_name: Data Science and ML
site_url: https://mydomain.org
site_author: Santosh Kumar Sah
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 


        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - content.tabs.link
    - header.autohide
    - content.code.annotate     # Enable annotated code
    - content.code.copy         # Add a copy button to code blocks
    - content.code.tabs         # Enable interactive tabs for code blocks
    - content.code.execute      # Enable interactive Python execution


  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/sntoshsah

nav:
  - Home: index.md
  - Projects:
      - AI Engineer: projects/ai.md
      - Data Science: projects/data_science.md
      - Machine Learning: projects/ML.md

  - Learning Resources:
    - Python Programming Concepts:
      - Learning_resources/Python/Python_Syntax.md
      - Learning_resources/Python/Python_Basics.md
      - Learning_resources/Python/Conditions_and_Loops.md
      - Learning_resources/Python/strings.md
      - Learning_resources/Python/List.md
      - Learning_resources/Python/Tuples.md
      - Learning_resources/Python/Sets.md
      - Learning_resources/Python/Dict.md
      - Learning_resources/Python/Functions.md
      - Learning_resources/Python/File_Handling.md
      - Learning_resources/Python/Exception_Handling.md
      - Learning_resources/Python/Methods.md
      - Learning_resources/Python/Decorators.md
      - Learning_resources/Python/Iterator_Generator_Duck_Typing.md
      - Learning_resources/Python/Functions_2.md
      - Learning_resources/Python/OOPs.md
      - Learning_resources/Python/Class.md
      - Learning_resources/Python/Objects.md
      - Learning_resources/Python/Method.md
      - Learning_resources/Python/Inheritance.md
      - Learning_resources/Python/Polymorphism.md
      - Learning_resources/Python/Data_Abstraction.md
      - Learning_resources/Python/Encapsulation.md
      - Learning_resources/Python/Constructors.md
      - Learning_resources/Python/Data_Member.md
      
    - DSA with Python:
      - Learning_resources/DSA/Introduction.md
      - Learning_resources/DSA/Asymptotic Notations.md
      - Learning_resources/DSA/Stack.md
      - Learning_resources/DSA/Queue.md
      - Learning_resources/DSA/Recursion.md
      - Learning_resources/DSA/Linked_List.md
      - Learning_resources/DSA/Sorting_Algorithms.md
      - Learning_resources/DSA/Searching_And_Hashing_Algorithms.md
      - Learning_resources/DSA/Trees_And_Graphs.md
      # - Learning_resources/DSA/Trees.md
      # - Learning_resources/DSA/Binary_Trees.md
      # - Learning_resources/DSA/Binary_Search_Trees.md
      # - Learning_resources/DSA/Binary_Heap.md
      # - Learning_resources/DSA/Huffman_Coding.md
      - Learning_resources/DSA/Dynamic_Programming.md
      - Learning_resources/DSA/Greedy_Algorithms.md


    - Machine Learning Algorithms and Concepts:
      - Learning_resources/Machine Learning/ML_basics.md
      - Learning_resources/Machine Learning/Regression.md
      - Learning_resources/Machine Learning/classification.md
      - Learning_resources/Machine Learning/Clustering.md
    - Deep Learning:
      - Learning_resources/Deep Learning/Neural_Network.md
      - Learning_resources/Deep Learning/Backpropagation.md
      - Learning_resources/Deep Learning/Optimizers.md
      - Learning_resources/Deep Learning/CNN.md
    - Data Science:
      - Learning_resources/Data Science/Statistics/Intro_to_Statistics.md
      - Learning_resources/Data Science/Statistics/probability.md
      - Learning_resources/Data Science/Statistics/Data_distribution.md
      - Learning_resources/Data Science/Statistics/correlation_and_experiment_design.md
      - Learning_resources/Data Science/Statistics/Hypothesis_testing.md
      - Learning_resources/Data Science/Statistics/Adv_Hypothesis_testing.md
      - Learning_resources/Data Science/Statistics/Hypothesis_testing_with_proportions.md
      - Learning_resources/Data Science/Statistics/Non_Parametric_test.md

    - Natural Language Processing:
      - Learning_resources/Data Science/NLP/roadmap.md
      - Learning_resources/Data Science/NLP/Introduction.md
      - Learning_resources/Data Science/NLP/Traditional NLP models.md
      - Learning_resources/Data Science/NLP/NLP with Deep Learning.md
      - Learning_resources/Data Science/NLP/Attention Mechanisms.md
    
    - Time Series:
      - Learning_resources/Time Series/roadmap.md
      - Learning_resources/Time Series/fundamentals.md
      - Learning_resources/Time Series/eda.md
      - Learning_resources/Time Series/Augmented Dickey-Fuller Test.md
      - Learning_resources/Time Series/preprocessing.md
      - Learning_resources/Time Series/fourier_series.md
      - Learning_resources/Time Series/Classical Time Series models.md
      - Learning_resources/Time Series/Arima.md
      - Learning_resources/Time Series/Exponential Smoothing.md
      - Learning_resources/Time Series/Machine Learning Techniques.md
      - Learning_resources/Time Series/Deep Learning Techniques.md
      - Learning_resources/Time Series/Advanced Time Series Concepts.md
      - Learning_resources/Time Series/Anamoly Detection.md


    - Data Visualization:
      - Learning_resources/Data Science/Data Visualization/Matplotlib.md
      - Learning_resources/Data Science/Data Visualization/Seaborn.md
      - Learning_resources/Data Science/Data Visualization/Plotly.md
      - Learning_resources/Data Science/Data Visualization/Plotly-2.md
      - Learning_resources/Data Science/Data Visualization/Geopandas.md

    - Mathematics:
      - Calculus:
        - Learning_resources/Mathematics/Calculus/Functions_on_One_Variable.md
        - Learning_resources/Mathematics/Calculus/Limit_And_Continuity.md
        - Learning_resources/Mathematics/Calculus/Derivative.md
        - Learning_resources/Mathematics/Calculus/Application_Of_Derivative.md
        - Learning_resources/Mathematics/Calculus/Integration.md
        - Learning_resources/Mathematics/Calculus/Integration Techniques.md
        - Learning_resources/Mathematics/Calculus/Application of antiderivatives.md
        - Learning_resources/Mathematics/Calculus/Ordinary differential Equations.md
        - Learning_resources/Mathematics/Calculus/Infinite Sequence and Series.md
        - Learning_resources/Mathematics/Calculus/Plane and Space Vectors.md
        - Learning_resources/Mathematics/Calculus/Partial Derivatives and Multiple Integrals.md
      - Linear Algebra:
        - Learning_resources/Mathematics/Linear Algebra/Linear Equations in Linear Algebra.md
        - Learning_resources/Mathematics/Linear Algebra/Transformations.md
        - Learning_resources/Mathematics/Linear Algebra/Matrix Algebra.md
        - Learning_resources/Mathematics/Linear Algebra/Determinants.md
        - Learning_resources/Mathematics/Linear Algebra/Vector Spaces.md
        - Learning_resources/Mathematics/Linear Algebra/Vector Spaces2.md
        - Learning_resources/Mathematics/Linear Algebra/Vector Spaces Continued.md
        - Learning_resources/Mathematics/Linear Algebra/Eigenvalues and Eigenvectors.md
        - Learning_resources/Mathematics/Linear Algebra/Orthogonality and Least Squares.md
        - Learning_resources/Mathematics/Linear Algebra/Ring and Field.md

    - DBMS:
      - Learning_resources/Data Science/DBMS/Normalization.md
      - Learning_resources/Data Science/DBMS/MySQL.md
      - Learning_resources/Data Science/DBMS/POSTGRESQL.md



    - Blog:
      - Learning_resources/Blog/Docker.md
      - Learning_resources/Blog/Linux_Commands.md
      - Learning_resources/Blog/Alembic.md
      - Learning_resources/Blog/sigmoid function.md


  - Contact: contact.md

plugins:
  - search
  - awesome-pages
  - mkdocs-jupyter
  - markdown-exec
  - glightbox
markdown_extensions:
- pymdownx.superfences:
    custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

- pymdownx.arithmatex:
    generic: true

- attr_list
- md_in_html
- pymdownx.blocks.caption

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js








