name: Deploy MkDocs Site

on:
  push:
    branches: [ "master" ]  # Trigger the workflow on pushes to the master branch
  pull_request:
    branches: [ "master" ]  # Trigger the workflow on pull requests to the master branch
  workflow_dispatch:        # Allow manual trigger of the workflow

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Adjust Python version as needed

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      # Build the MkDocs site
      - name: Build MkDocs Site
        run: mkdocs build --strict

      # Deploy the MkDocs site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
          publish_dir: site  # Directory containing the built MkDocs site
