# Workflow for building and deploying an MkDocs site to GitHub Pages
name: Deploy MkDocs Site to GitHub Pages

on:
  # Trigger the workflow on pushes to the master branch
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build and Deploy job
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install MkDocs and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          pip install -r requirement.txt

      # Build the MkDocs site
      - name: Build MkDocs Site
        run: mkdocs build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
